spring.application.name=whisper-api-lab

# Tamanho máximo do arquivo para upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.ai.google.genai.chat.options.model=gemini-2.0-flash
