spring.application.name=whisper-api-lab
#transcription.api.url=https://api.openai.com/v1
#transcription.api.key=${OPENAI_API_KEY}

# Tamanho máximo do arquivo para upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.ai.google.genai.chat.options.model=gemini-2.0-flash
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
